server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://discovery-service-food-app.herokuapp.com/eureka/}
  instance:
    instance-id: frontend-instance
spring:
  application:
    name: frontend
